module Rubylox
  class Environment
    attr_reader values: ::Hash[::String, untyped]
    attr_reader enclosing: Environment?

    def initialize: (Environment? enclosing) -> void
    def define: (string name, untyped value) -> untyped
    def ancestor: (int distance) -> Environment
    def get: (Token name) -> Object
    def get_at: (int distance, string name) -> Object
    def assign: (Token name, untyped value) -> void
    def assign_at: (int distance, Token name, untyped value) -> void
  end
end
