module Rubylox
  class Environment
    attr_reader values: ::Hash[::String, untyped]
    attr_reader enclosing: Environment?

    def initialize: (Environment? enclosing) -> void
    def define: (string name, untyped value) -> untyped
    def get: (Token name) -> untyped
  end
end
