module Rubylox
  class LoxInstance
    def initialize: (Class kclass) -> void
    def get: (Token name) -> Object
    def set: (Token name, Object value) -> void
    def to_s: () -> ::String

    attr_reader klass: Class
    attr_reader fields: Hash[Token, Object]
  end
end
