module Rubylox
  class LoxCallable
    def call: (Interpreter interpreter, [Object] arguments) -> Object
  end

  class LoxFunction
    attr_reader declaration: FunctionStmt
    attr_reader closure: Environment

    def arity: () -> int
    def initialize: (FunctionStmt declaration) -> void
    def call: (Interpreter interpreter, [Object] arguments) -> Object
    def bind: (LoxInstance) -> LoxFunction
  end

  class ReturnException < StandardError
    attr_reader value: Object
    def initialize: (Object value, string? message) -> void
  end
end
