module Rubylox
  class TokenType
    attr_reader type: ::Symbol  #:and | :class | :else | :false |
      #:for | :fun | :if | :nil | :or | :print | :return |
      #:super | :this | :true | :var | :while | :eof | :error |
      #:identifier | :string | :number | :left_paren | :right_paren |
      #:left_brace | :right_brace | :comma | :dot | :minus | :plus |
      #:semicolon | :slash | :star | :bang | :bang_equal | :equal |
      #:equal_equal | :greater | :greater_equal | :less | :less_equal

    def initialize: (::Symbol) -> void
    def ==: ((TokenType | ::Symbol) other) -> bool
  end

  class Token
    def initialize: (::Symbol, untyped lexeme, untyped literal, untyped line) -> void

    attr_reader type: untyped

    attr_reader lexeme: untyped

    attr_reader literal: untyped

    attr_reader line: untyped

    def to_s: () -> ::String
  end
end
